apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databasetables.kopf.demo
spec:
  scope: Namespaced
  group: kopf.demo
  names:
    kind: DatabaseTable
    plural: databasetables
    singular: databasetable
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["tableName","columns","primaryKey"]
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true