---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: database-table-operator-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: database-table-operator-role
rules:
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  - apiGroups: [kopf.demo]
    resources: [databasetables]
    verbs: [create, list, watch, patch]

  - apiGroups: [""]
    resources: [secrets]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: database-table-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: database-table-operator-role
subjects:
  - kind: ServiceAccount
    name: database-table-operator-account
    namespace: default